### ISSUE TITLE
Sudo crontab

### ISSUE THREAD

**Issue by mikulik86** [rovellipaolo/gnome-shell-extension-sermon#16]
Hi,
could it be also possible to monitor also sudo cron jobs?

(Otherwise very nice extension! 😉)

**Comment by rovellipaolo** [comment]
Mmm.. to be "possible" it's possible, for example by launching `sudo crontab -l`. The problem with it is that the end-user would need to enter the password when the extension is opened, which is something I don't like.
I _might_ think about adding it as an optional feature, with a config to enable/disable it. But don't expect it any time soon.

**Comment by mikulik86** [comment]
You mean enter the password every time the extension launches (like after each login)? Or only once during setting?

**Comment by rovellipaolo** [comment]
> You mean enter the password every time the extension launches (like after each login)? Or only once during setting?

Every time the extension is launched. More specifically, when one clicks on the extension icon/button in the GNOME tray.
It won't probably be every single time, due to cached permissions, but not really sure. I will need to play with it and see what can be done.

**Comment by mikulik86** [comment]
Well, this doesn't sound very practically. Anyway, thanks for your interest.
