### ISSUE TITLE
Error service name

### ISSUE THREAD

**Issue by gpibarra** [rovellipaolo/gnome-shell-extension-sermon#20]
If services contain a "." (dot) only the above is shown
For example, I have the services
`php8.2-fpm` and `php8.1-fpm` and both are displayed as `php8`

**Comment by rovellipaolo** [comment]
Good catch! Should be fixed now: https://github.com/rovellipaolo/gnome-shell-extension-sermon/commit/7aa517b239a541e7d40cd12c77c47ba47ca8ecd4
Please, try the latest version (i.e., 25) of the extension.
