### ISSUE TITLE
Show only services in priority list?

### ISSUE THREAD

**Issue by GiovanniCardamone** [rovellipaolo/gnome-shell-extension-sermon#3]
It would be nice if i can filter only services in priority list

p.s. Great extension! :muscle:

**Comment by rovellipaolo** [comment]
Hello! I'm not totally sure I've understood your request correctly. 

The list of Systemd services is currently extracted using the following command:
```
$ systemctl list-units --type=service --all --system
```
With the `--system` flag that is replaced by the `--user` one if the _"Show only user services"_ option is enabled.
And the priority list is just a comma-separated list of services that will be shown first.

Could you give me more details on which is your need?

**Comment by GiovanniCardamone** [comment]
For example I want my list of services shows only:
- Apache 
- Mysql
- Cron
- etc

So maybe a switch with option
(Show only services in priority list)
So I don't have to Watch Bluetooth and other services.

**Comment by rovellipaolo** [comment]
Ah.. sorry, I had completely misunderstood your original question.
Sure, that should be pretty easy to implement. :)

**Comment by GiovanniCardamone** [comment]
Yey thanks a lot! i will stay tuned :)

**Comment by rovellipaolo** [comment]
Done: [d990e5ad760ba39384a7735f483bc3987371adaa](https://github.com/rovellipaolo/gnome-shell-extension-sermon/commit/d990e5ad760ba39384a7735f483bc3987371adaa) :)

This feature is now integrated in the `master` branch, and also [backported to the `gnome-shell-3-28` branch](https://github.com/rovellipaolo/gnome-shell-extension-sermon/commit/53cf6289a2d5f4427c08c8841b14ff0a54813223).
It will be available starting from version 10 of SerMon, which I've already submitted to the [GNOME Extensions](https://extensions.gnome.org/extension/1804/sermon/) page. 

Finally, I've taken the chance also to support both ids and names in the priority list (i.e. now you can use both _"mysql.service"_ and simply _"mysql"_) and improve a bit the testing of the filtering/ordering logic.
