### ISSUE TITLE
Gnome 3.38.1 - TypeError: meta is null

### ISSUE THREAD

**Issue by prolific** [rovellipaolo/gnome-shell-extension-sermon#4]
I tried installing this extension in Gnome version 3.38.1 but looks like I am unable to make it work.

In logs I am seeing this error:
`JS ERROR: Extension sermon@rovellipaolo-gmail.com: TypeError: meta is null`

Stacktrace:
```
JS ERROR: Extension sermon@rovellipaolo-gmail.com: TypeError: meta is null
_patchContainerClass/containerClass.prototype.child_set@resource:///org/gnome/shell/ui/environment.js:43:13
_patchContainerClass/containerClass.prototype.add@resource:///org/gnome/shell/ui/environment.js:52:18
showHeader@/home/prolific/.local/share/gnome-shell/extensions/sermon@rovellipaolo-gmail.com/src/presentation/views.js:115:29
setupView@/home/prolific/.local/share/gnome-shell/extensions/sermon@rovellipaolo-gmail.com/src/presentation/presenters.js:106:19
SectionPresenter@/home/prolific/.local/share/gnome-shell/extensions/sermon@rovellipaolo-gmail.com/src/presentation/presenters.js:102:14
_init@/home/prolific/.local/share/gnome-shell/extensions/sermon@rovellipaolo-gmail.com/src/presentation/views.js:103:30
buildSectionView@/home/prolific/.local/share/gnome-shell/extensions/sermon@rovellipaolo-gmail.com/src/presentation/views.js:76:20
_addSection@/home/prolific/.local/share/gnome-shell/extensions/sermon@rovellipaolo-gmail.com/src/presentation/presenters.js:41:39
setupView/<@/home/prolific/.local/share/gnome-shell/extensions/sermon@rovellipaolo-gmail.com/src/presentation/presenters.js:37:56
setupView@/home/prolific/.local/share/gnome-shell/extensions/sermon@rovellipaolo-gmail.com/src/presentation/presenters.js:37:23
_init@/home/prolific/.local/share/gnome-shell/extensions/sermon@rovellipaolo-gmail.com/src/presentation/views.js:27:28
enable@/home/prolific/.local/share/gnome-shell/extensions/sermon@rovellipaolo-gmail.com/extension.js:19:13
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:586:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:565:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:595:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:626:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:269:22
start@resource:///org/gnome/shell/ui/main.js:159:5
@<main>:1:47
```

Let me know if there is any further information I can share.

**Comment by rovellipaolo** [comment]
Hello there!
As specified in the _README.md_, this extension did not support GNOME Shell 3.38 yet.

Having a look at it, it would seem that the `St.BoxLayout` child meta was deprecated in the previous 3.36 version and now in the latest 3.38 version finally removed (see: [https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3264](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3264)).
I've [fixed it](https://github.com/rovellipaolo/gnome-shell-extension-sermon/commit/b06941054bbd10b33ff844291e507b1124b0645c) and added support for GNOME Shell 3.38 starting from version 12 of the extension. ;)

**Comment by prolific** [comment]
@rovellipaolo Thanks for the quick upgrade. Appreciate it. 
I did notice the support limitation so I tried to make the extension myself by commenting the line with error but it still didn't work  functionally.

Anyway, I will try the v12 later today and see if it works as expected.

Off topic: Is there any support of intellisense for Gnome Javascript (GJS) yet (preferably for vscode)? Or shell extensions still need to be developed by referring to the official documentation?

**Comment by rovellipaolo** [comment]
@prolific sorry for the late reply. Regarding intellisense support, not as far as I know.
But, at least, nowadays most of the code is standard JavaScript. For example, in SerMon, almost all the GJS-specific code is relegated to the views (with the exception of the command-line wrapper).
Therefore, you can take advantage of most of JavaScript tooling out there, such as: `eslint`, `prettier`, etc...
