### ISSUE TITLE
Stopped service missing at login

### ISSUE THREAD

**Issue by GiovanniCardamone** [rovellipaolo/gnome-shell-extension-sermon#5]
Hello, (again :smile: )

i am using :

```
$ gnome-shell --version
GNOME Shell 3.36.4
```
![Imgur](https://i.imgur.com/oaNADea.png)

i disabled most of the service at start

example
```
# systemctl disable mongodb
```

and services are not listed in panel

![Imgur](https://i.imgur.com/xW98c7z.png)

full `Service priority list` field content:

```
nginx, docker, mongodb, redis-server, apache2
```

am i doing something wrong or is supposed tho worki in this way?

it will be cool to have also stopped service to start it manually only if i needed

for example mongodb service is in this status:

```
# service mongodb status
● mongodb.service - An object/document-oriented database
     Loaded: loaded (/lib/systemd/system/mongodb.service; disabled; vendor pres>
     Active: inactive (dead)
       Docs: man:mongod(1)
```

**Comment by rovellipaolo** [comment]
Hi! No, it's not supposed to work that way.
I will have a look at it.

**Comment by GiovanniCardamone** [comment]
if you need more informations, just let me know

**Comment by rovellipaolo** [comment]
Could you please try to execute the following commands?
```
$ systemctl list-units --type=service --all --system | grep mongodb
$ systemctl list-units --type=service --all --user | grep mongodb
```
And also:
```
$ systemctl --version
```

**CONTEXT:**
Currently the Systemd services are extracted using the above commands (i.e. `systemctl list-units --type=service --all`).
Not really sure if I should use a different command instead. But, as far as I could see, it seems that some versions of Systemd are not returning the disabled services as part of that command response. For example, in my case, it works well with Systemd version _246_  but not with version _245_.

**Comment by GiovanniCardamone** [comment]
Also the option for enable/disable from monitor would be great!

I know maybe is a lot of work. I love this tool and is working like a charm.

It's still a wonderful tool even without those changes :)

**Comment by rovellipaolo** [comment]
Sorry for not giving you any update, I was a bit busy. Anyway, [done](https://github.com/rovellipaolo/gnome-shell-extension-sermon/commit/9bc816302ebafacd3ba51a9d80cbc73340424118)! :)
You should see this new functionality starting from version 13 of the extension.

**NOTE:** At least for the moment, you will be able to enable/disable only the services whose status is _"enabled"_, _"enabled-runtime"_, _"generated"_ or _"disabled"_. Or, in other words, you won't see the add/remove button for example for services that are masked or not found.

**Comment by GiovanniCardamone** [comment]
Is already available throught extension.gnome.org?

i did not get the updates

**Comment by rovellipaolo** [comment]
It's already submitted, but not yet available. Usually the review process takes a couple of days at most. :)
![Screenshot from 2021-04-14 14-48-03](https://user-images.githubusercontent.com/3950191/114712724-b5432680-9d30-11eb-9391-ac6d701f5105.png)

**Comment by GiovanniCardamone** [comment]
lovely!

**Comment by rovellipaolo** [comment]
Version 13 should be now available. :)
I quote myself, just as a reminder (to manage expectations):
> NOTE:
> At least for this version, the "show all" option will be disabled by default and you'll need to enable it manually from the extension settings. This is for couple of reasons, the most important of them being the fact that the performance are not really good. I'll try to improve them in future versions. :)
> Also, at present, you will be able to enable/disable only the services whose status is "enabled", "enabled-runtime", "generated" or "disabled". Or, in other words, you won't see the add/remove buttons for example for services that are masked or not found.

**Comment by GiovanniCardamone** [comment]
beautiful!

work like a charm

Thanks a lot!
