### ISSUE TITLE
Click on the extension starts Docker service if Docker section is active

### ISSUE THREAD

**Issue by marcelopbarros** [rovellipaolo/gnome-shell-extension-sermon#8]
Hi guys!

I'd like to suggest an improvement for people that optionally uses Docker service. I realize I can stop Docker service as usual but when I click on the extension the Docker service starts again. I think that happens because of the listing of Docker containers. When I disable the Docker containers list on the extension config that doesn't happen anymore and the Docker service stays stopped as expected.

I used the following command to check status of the service: `watch sudo systemctl status docker`

![screenshot](https://user-images.githubusercontent.com/12131038/146033869-29fa5e7d-d3d2-44e1-aaaa-cea2e055709b.png)

So, my suggestion is that when the Docker service is stopped the extension avoid list Docker containers and their status, maybe showing a message on place of the containers list like "Docker service is inactive" or even hiding Docker section entirely.

Because a lot of people can be used to the actual behaviour, a good choice would be add another option to the Docker extension config maybe labeling as "Show Docker container only when service is running", something like that.

![screenshot2](https://user-images.githubusercontent.com/12131038/146036045-0cab201b-77df-44cb-b811-6539a8ad73c2.png)

Thank you guys for the awesome work and the great idea!

**Comment by rovellipaolo** [comment]
Hello! First of all, sorry for the far too late reply.
You are correct, listing Docker images (i.e. launching _"docker ps"_) is automatically restarting the Docker systemd service. Will fix it!

**Comment by rovellipaolo** [comment]
Fixed: https://github.com/rovellipaolo/gnome-shell-extension-sermon/commit/6a33ddfac38d479ee6687d2b25e819a30ab979ed
The fix has been released with version 21 of the extension.

Note that, in the end, I've not added any new settings: if Docker service is not running, the images are simply not listed.
![Screenshot 2022-11-25 175117](https://user-images.githubusercontent.com/3950191/204028890-cb498595-5b4a-4a5a-9e0e-1eda27f722e0.png)
